### PR TITLE
#1515. Copyright header rule for Kotlin files.

### PR DESCRIPTION
**Pull request by dector**
:construction: _Draft_

### CODE REVIEW

**Comment by dector** [comment]
Added `location` property to config. Do you think it's a way to go or should I explore other solutions?

**Comment by arturbosch** [comment]
I like the `location` idea.
It brings to me the idea that we can use the `Config` as a "data container", storing/caching additional information before actually performing the run (`HashMap`).
The hard part is that the additional information step is rule dependant.
So basically we need to have a new method for `Rule` like `initData(config: Config)` which runs once before the visiting process of the KtFile's.
For this we need to call `initData` in the `core` module in the main thread.
This sounds like a generic way for rules to cache data between KtFile's.

**Comment by dector** [comment]
Glad that you've liked that. 

> This sounds like a generic way for rules to cache data between KtFile's.

Sounds awesome! Will explore it. Probably, I'll not have enough time in next 10 days, but will try to find short time-frames.

**Comment by dector** [comment]
Sorry for the delay. :sweat_smile: 

Let me double check your suggestions:
  - Should `Config` serve a purpose of data cache for rules? I'm not sure that it's a very good idea as it'll bloat responsibilities for the class. Besides that what should be do with other config implementations (`CompositeConfig` and `Rule` itself as it's extending `ConfigAware` that is extending `Config`)?
  - Do you mean that `rule.initData()` should be invoked somewhere in `Detektor.run()` (or `runSync`/`runAsync`). If I get it right, we'll need to build rule sets once more for this. Is that a lightweight operation?

Thanks!

**Comment by schalkms** [comment]
Sorry for the late answer @dector 
 - ping @arturbosch

**Comment by arturbosch** [comment]
I've rebased on top of master and implemented a way to share the cache license header for this rule.
However I can't push my changes to this PR for whatever reasons...

Normally I check out the fork of a contributor, do some changes and can push them back to this branch. Maybe this time I'm not allowed to do this because it is a draft or something?

**Comment by BraisGabin** [comment]
That's a permission that the author of the PR can give [when the PR is created](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by arturbosch** [comment]
@dector please allow me to push to this branch :)

**Comment by dector** [comment]
@arturbosch Hm.. "Edits from maintainers" are enabled for this PR. Let me undraft it.

**Comment by arturbosch** [comment]
Unfortunately I couldn't push into this PR and created a new PR with the caching changes :(

**Pull request closed without merging**
