### PR TITLE
Improve build setup

### PR DESCRIPTION
**Pull request by rock3r**
This PR contains three main chunks of work, aimed at improving the build setup and timings taking advantage of Gradle's [compile avoidance](https://guides.gradle.org/performance/#compile_avoidance) and incremental compilation:

 * Update Gradle to v4.1-rc2 [_changelog_](https://docs.gradle.org/4.1-rc-2/release-notes.html)
    * This includes updating the wrapper, too
 * Clean up the build files' strings, using single quotes wherever possible to maintain consistency
 * The meatiest bit is to use the new `implementation` APIs for all modules, which allows Gradle to only selectively build modules whose code has changed
   * I have one instance of `compile` left, because the `api` configuration doesn't seem to exist in the current setup (I suspect the Kotlin plugin might be the cause). It is functionally the same thing, and we'll eventually be able to move this to `api` too, I hope

I have run tests and checked it all still compiles; what I have not been able to test is publishing to maven (but that should not be impacted). I don't have hard numbers but when running tests on `detekt-rules` (for another PR) I have noticed it is now much much faster than it was. Sorry it's only anecdotal evidence :(

Note: all changes in the `gradle` folder were automatically performed by Gradle itself when upgrading with `./gradlew wrapper --gradle-version=4.1-rc-2`

### CODE REVIEW

**Comment by arturbosch** [comment]
Looks good to me, will check it out later on my machine. Thanks a lot!

**Comment by rock3r** [comment]
I have a PR ready to open with a big bugfix for `MagicNumber` once this is merged 👍

**Comment by arturbosch** [comment]
Everything seems to work including maven publish to bintray. I do not see any performance benefits from 20 test runs but implementation is the new preferred way I read, thanks you for this :)

**Comment by arturbosch** [comment]
Ok maybe I was too fast for this, the cli does not run anymore. Kotlin Instristics etc ... maybe cli needs everything as api not implementation>

**Comment by rock3r** [comment]
Hmm that would be weird, `api` means that other modules which depends on `cli` will transitively get those too. But it didn't seem to be the case? I'll have a look at the CI

**Comment by rock3r** [comment]
Oh also, you will get perf improvements in incremental runs where only one leaf module was changed. `clean`s and changing root modules (e.g., `api`) can cause times to be the same as they were.

**Comment by rock3r** [comment]
I checked out `master`, ran `./gradlew detekt-cli:build`, grabbed the zipped distribution, and tried it against the [Squanchy](https://squanchy.net) codebase. Everything seems to work just fine:

```
$ ./detekt-cli -i ~/src/squanchy/ -c ~/src/squanchy/team-props/static-analysis/detekt-config.yml 
Analyzing 36 kotlin files: ....................................

Ruleset: code-smell
Ruleset: comments
Ruleset: complexity
Ruleset: empty-blocks
Ruleset: exceptions
Ruleset: performance
Ruleset: potential-bugs
Ruleset: style
	MagicNumber - [<anonymous>] at app/src/main/java/net/squanchy/schedule/domain/view/Event.kt:41:80
	MagicNumber - [<anonymous>] at app/src/main/java/net/squanchy/schedule/ScheduleService.kt:67:90
	MagicNumber - [credential] at app/src/main/java/net/squanchy/service/firebase/FirebaseAuthService.kt:23:88
	ReturnCount - [observeChildAndEmit] at app/src/main/java/net/squanchy/service/firebase/FirebaseDbService.kt:82:5
	MagicNumber - [<anonymous>] at app/src/main/java/net/squanchy/service/firebase/FirebaseDbService.kt:108:62
	MagicNumber - [id] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseDay.kt:3:42
	MagicNumber - [date] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseDay.kt:3:68
	MagicNumber - [days] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseDays.kt:3:56
	MagicNumber - [id] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseEvent.kt:4:27
	MagicNumber - [name] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseEvent.kt:5:29
	MagicNumber - [type] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseEvent.kt:6:29
	MagicNumber - [start_time] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseEvent.kt:7:33
	MagicNumber - [end_time] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseEvent.kt:8:31
	MagicNumber - [day_id] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseEvent.kt:9:31
	MagicNumber - [description] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseEvent.kt:10:36
	MagicNumber - [track_id] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseEvent.kt:11:33
	MagicNumber - [experience_level] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseEvent.kt:12:41
	MagicNumber - [place_id] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseEvent.kt:13:33
	MagicNumber - [speaker_ids] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseEvent.kt:14:42
	MagicNumber - [links] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseEvent.kt:15:37
	MagicNumber - [events] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseEvents.kt:3:69
	MagicNumber - [slides] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseLinks.kt:3:48
	MagicNumber - [id] at app/src/main/java/net/squanchy/service/firebase/model/FirebasePlace.kt:4:27
	MagicNumber - [name] at app/src/main/java/net/squanchy/service/firebase/model/FirebasePlace.kt:5:29
	MagicNumber - [floor] at app/src/main/java/net/squanchy/service/firebase/model/FirebasePlace.kt:6:30
	MagicNumber - [places] at app/src/main/java/net/squanchy/service/firebase/model/FirebasePlaces.kt:3:57
	MagicNumber - [id] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseSpeaker.kt:4:27
	MagicNumber - [name] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseSpeaker.kt:5:29
	MagicNumber - [bio] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseSpeaker.kt:6:28
	MagicNumber - [company_name] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseSpeaker.kt:7:37
	MagicNumber - [company_url] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseSpeaker.kt:8:36
	MagicNumber - [personal_url] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseSpeaker.kt:9:37
	MagicNumber - [twitter_username] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseSpeaker.kt:10:41
	MagicNumber - [photo_url] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseSpeaker.kt:11:34
	MagicNumber - [speakers] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseSpeakers.kt:4:48
	MagicNumber - [id] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseTrack.kt:4:27
	MagicNumber - [name] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseTrack.kt:5:29
	MagicNumber - [accent_color] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseTrack.kt:6:37
	MagicNumber - [text_color] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseTrack.kt:7:35
	MagicNumber - [icon_url] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseTrack.kt:8:33
	MagicNumber - [tracks] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseTracks.kt:4:44
	MagicNumber - [favorites] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseUserData.kt:4:48
	MagicNumber - [achievements] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseUserData.kt:5:48
	MagicNumber - [name] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseVenue.kt:4:29
	MagicNumber - [address] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseVenue.kt:5:32
	MagicNumber - [lat] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseVenue.kt:6:28
	MagicNumber - [lon] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseVenue.kt:7:28
	MagicNumber - [description] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseVenue.kt:8:36
	MagicNumber - [map_url] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseVenue.kt:9:32
	MagicNumber - [timezone] at app/src/main/java/net/squanchy/service/firebase/model/FirebaseVenue.kt:10:33

Complexity Report:
	- 547 logical lines of code (lloc)
	- 4 comment lines of code (cloc)
	- 91 McCabe complexity (mcc)
	- 50 number of total code smells
	- 166 mcc per 1000 lloc
	- 91 code smells per 1000 lloc

Project Statistics:
	- number of properties: 16
	- number of functions: 79
	- number of classes: 46
	- number of packages: 13
	- number of kt files: 36

Exception in thread "main" io.gitlab.arturbosch.detekt.cli.console.BuildFailure: Build failure threshold of 1 reached with 50 weighted smells!
	at io.gitlab.arturbosch.detekt.cli.console.BuildFailureReport.render(BuildFailureReport.kt:34)
	at io.gitlab.arturbosch.detekt.api.ConsoleReport.print(ConsoleReport.kt:11)
	at io.gitlab.arturbosch.detekt.cli.OutputFacade.handleConsoleReport(OutputFacade.kt:51)
	at io.gitlab.arturbosch.detekt.cli.OutputFacade.run(OutputFacade.kt:36)
	at io.gitlab.arturbosch.detekt.cli.Runner.execute(Runner.kt:22)
	at io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt:19)
```

(except the ton of `MagicNumber` issues, which were the reason I ended up working on #278)

**Pull request merged**
