### PR TITLE
Lazily attach to check task

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Previously, applying Detekt plugin would result in `check` task and potentially its dependencies being configured.

PR also improves naming of the functions, since they now don't create and configure Gradle tasks but register and lazily configure them.

@vanniktech was sitting at the same desk during this code change, so he's added as author too lol

### CODE REVIEW

**Comment by glebsts** [comment]
Hi, sorry for posting to closed PR, but its probably the closest thing to my problem I found. RC11 was published 17 days agom and this was merged 10 days ago, so mb..
I get following when configuring `detekt` in `subprojects` in external gradle script:
```org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':check'.
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:66)
	at org.gradle.execution.taskgraph.TaskDependencyResolver.resolveDependenciesFor(TaskDependencyResolver.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfo.getDependencies(LocalTaskInfo.java:89)
	at org.gradle.execution.taskgraph.LocalTaskInfo.resolveDependencies(LocalTaskInfo.java:62)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.addToTaskGraph(DefaultTaskExecutionPlan.java:168)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.addTasks(DefaultTaskExecutionGraph.java:126)```
...
`Caused by: org.gradle.internal.typeconversion.UnsupportedNotationException: Cannot convert io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated@73a6a585 to a task.`

external.gradle:
```
subprojects {
  apply plugin: io.gitlab.arturbosch.detekt.DetektPlugin
  detekt {
    // ...
  }
  check.dependsOn detekt
}
```

Can it be same and I need new release, or should I raise new issue?
Thank you.

**Comment by arturbosch** [comment]
Hey, it could be, lets wait for the last ticket on RC12 to be merged and I will release a new vesion you can try out, sorry for the wait.

**Comment by artem-zinnatullin** [comment]
@glebsts I think it happens because of this line in your `external.gradle`

```
check.dependsOn detekt
```

You're referencing `detekt` which is indeed a configuration extension rather than a task which is what Gradle complaints about according to stacktrace and message.

You actually don't need that line at all, Detekt Plugin already adds exact that behavior — `check` task (if present) will depend on `detekt` task.

There is as integration test that verifies this behavior and this PR passed it :)

**Comment by arturbosch** [comment]
Yes please create a new issue, thanks :)

**Pull request merged**
