### PR TITLE
fix compile erros in the detekt-gradle-plugin project

### PR DESCRIPTION
**Pull request by Mauin**
While rebasing #771 and trying to check some of the behavior on `master` I couldn't get the project to compile without these changes.

### CODE REVIEW

**Comment by Mauin** [comment]
😕 What is different in my local build with IntelliJ to the CI build? It fails for exactly the code that was changed. This is confusing.

**Comment by arturbosch** [comment]
Do you use gradle 4.7 ? I noticed some errors with that version and it does complain about the kotlin-dsl :/

**Comment by Mauin** [comment]
#877 fixes the issues with the new Gradle version as the Kotlin DSL had quite a few changes.

**Comment by arturbosch** [comment]
Is this still relevant? I get compile errors when removing the `it`'s.

**Comment by Mauin** [comment]
Seems to have been an issue with IntelliJ. I updated IntelliJ to a newer version and now `master` works fine for me again.

**Pull request closed without merging**
