### PR TITLE
Exclude LongMethod in tests by default.

### PR DESCRIPTION
**Pull request by vanniktech**
I don't feel like this rule should be on for tests. Often a longer more descriptive test is better than a short comprehensive one that's not understandable.

### CODE REVIEW

**Comment by arturbosch** [comment]
What for do you need more than tweenty lines of code in your tests? oO

**Comment by vanniktech** [comment]
When setting up a few things for a particular test. I wouldn't say it's that uncommon. If we wouldn't use the file system for testing, we'd execute it almost every single time.

**Comment by schalkms** [comment]
I also don't quite like this setting. I can live with a slightly higher threshold for the test package, but I wouldn't want to disable this check for test methods completely.

**Comment by vanniktech** [comment]
Makes sense. So should we close this then?

**Comment by schalkms** [comment]
I would say so.

**Pull request closed without merging**
