### PR TITLE
Improve SuppressSpec test

### PR DESCRIPTION
**Pull request by MyDogTom**
* ~use threshold for rules, otherwise they do not detect error~
 * added MaxLineLength to test

Test are failing now.
For `MaxLineLength`  suppress doesn't work on class and element level
~For `LongMethod` suppress doesn't work on element level~

Unfortunately, I'm not familiar enough with "visitors" to quickly fix it :(

### CODE REVIEW

**Comment by MyDogTom** [comment]
Sorry, I misunderstood how `threshold` works. Removed this change. Only `MaxLineLength` do not work.

**Comment by MyDogTom** [comment]
Ok, now I see that `MaxLineLength` rule works on file level. It means that it can be suppressed only on file level. Not very helpful, as ideally I'd like to suppress only one statement.
I also haven't found any way to understand on which level suppress works for the rule . Only by digging into rule implementation :(

**Comment by arturbosch** [comment]
Yes it is not quite `clear` for the user which rule works on which level...

The MaxLineLength rule also does not use the classic visitor approach ... we could change it to visit each statement and check each line of that statement, then it would be suppressible by statement, method, class and file hmm, what do you think?

**Comment by MyDogTom** [comment]
>then it would be suppressible by statement, method, class and file hmm, what do you think?

I think suppressing `MaxLineLength` is not highly requested feature. I'm not sure, if it's worth to do it. At least now. In my case, I had long `json` expected value in test. I've managed to "get rid of it" :)

What is more important (from my point of view) is to have easily accessible wiki/documentation/whatever where end user can find information about rule and which `suppress` level is supported. I'm sure you have plans for that :)

**Comment by arturbosch** [comment]
Good point on mentioning suppress level in documentation!

**Pull request closed without merging**
