### PR TITLE
Do not add +1 complexity for nested functions inside functions

### LINKED ISSUE #1037: ComplexMethod false positive for returning anonymous inner class
## Expected Behavior
No detection.

## Current Behavior
```
ComplexMethod - 11/10 - [f] at  ...
```

## Steps to Reproduce (for bugs)
Run `ComplexMethod` on this:
```kotlin
fun f(): List<Any> {
    return object : List<Any> {
        override val size: Int get() = TODO("not implemented")

        override fun contains(element: Any): Boolean {
            TODO("not implemented")
        }

        override fun containsAll(elements: Collection<Any>): Boolean {
            TODO("not implemented")
        }

        override fun get(index: Int): Any {
            TODO("not implemented")
        }

        override fun indexOf(element: Any): Int {
            TODO("not implemented")
        }

        override fun isEmpty(): Boolean {
            TODO("not implemented")
        }

        override fun iterator(): Iterator<Any> {
            TODO("not implemented")
        }

        override fun lastIndexOf(element: Any): Int {
            TODO("not implemented")
        }

        override fun listIterator(): ListIterator<Any> {
            TODO("not implemented")
        }

        override fun listIterator(index: Int): ListIterator<Any> {
            TODO("not implemented")
        }

        override fun subList(fromIndex: Int, toIndex: Int): List<Any> {
            TODO("not implemented")
        }
    }
}
```

## Context
The method is quite simple:
```kotlin
fun f(): List<Any> {
    return object : List<Any> { ... }
}
```

## Your Environment

* Version used: 1.0.0.RC7-3
* Operating System and version: Windows 10
* Link to your project: private but full repro provided above

### PR DESCRIPTION
**Pull request by arturbosch**
Closes #1037

### CODE REVIEW

**Comment by Mauin** [comment]
What about local functions? imo those still should increase the complexity and are different from the case we're trying to address here.

**Comment by arturbosch** [comment]
Hm, one can argue that local functions help to declutter and structurize your code, removing nestings etc removes complexity. Like an algorithm which implementation is a whole function with many little helper local functions. I would't call this code complex but rather an architectural choice to build it this way :)?

**Comment by schalkms** [comment]
I also agree with @Mauin 
I think the complexity of nested functions should be taken into account. The reported issue was in regard to overridden functions from an object.

**Comment by arturbosch** [comment]
Ok, I changed to skip functions inside object literals :)

**Comment by arturbosch** [comment]
@schalkms @Mauin still approved :)?

**Pull request merged**
