### PR TITLE
Don't publish Gradle plugin to Bintray

### PR DESCRIPTION
**Pull request by 3flex**
Doesn't seem there's any value in pushing anything related to the Gradle plugin to Bintray, or synced to Maven Central (and it doesn't look like anything's being pushed there at the moment), so makes sense to remove the config from the Gradle plugin build file.

Kept this separate to #1151 since that's about simplifying the script but not changing build behavior, where this change might affect some workflow I'm not aware of.

### CODE REVIEW

**Comment by arturbosch** [comment]
Hm, if I'm not wrong the bintray publishing was neccesary for something .... but I do not remember why anymore ... Will leave this open for now and come to it later.

**Comment by arturbosch** [comment]
For the next release I won't publish the gradle plugin to bintray and see if we need it somehow.

**Comment by arturbosch** [comment]
Couldn't test this really because the gradle folks started to check the plugins before making them public and I thought it does not work because of the bintray stuff :D.
But I will try to release faster now :D.

**Comment by 3flex** [comment]
In that case I expect you can still use the plugin hosted on the Gradle Plugin Portal (tweak syntax for Kotlin DSL if you're using that):

```gradle
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0-RC10"
  }
}

apply plugin: "io.gitlab.arturbosch.detekt"
```

**Comment by jayrave** [comment]
Didn't know about depending on the plugin portal itself. Thanks! All I had to do was add a new repository & a dependency

```kotlin
plugins {
    `kotlin-dsl`
}

repositories {
    maven("https://plugins.gradle.org/m2/")
    google()
    jcenter()
}

dependencies {
   compile("com.android.tools.build:gradle:3.2.1")
    compile("io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0-RC10")
}
```

**Comment by arturbosch** [comment]
Seems like bintray publishing is not needed :), will try for next release to delete it and publish the plugin, maybe the publishing plugin is needed for `pluginPublish`task ^^

**Comment by arturbosch** [comment]
Cherry-picked into 6cfaaee721bdb44ba8613e014f98355a8884fb28, thanks!

**Pull request closed without merging**
