### PR TITLE
Allow numbers in ClassNaming.

### LINKED ISSUE #169: Default NamingConventionViolation classPattern does not allow numbers
The regex is `'[A-Z$][a-zA-Z$]*'` which does not allow digits. Is this done on purpose?

### PR DESCRIPTION
**Pull request by vanniktech**
Fixes #169

### CODE REVIEW

**Comment by vanniktech** [comment]
I ran `build` locally and I don't have any diff changes for the config file. Is there a difference between my computer (mac) and travis (linux)? I'm also unsure why the order was swapped.

**Comment by schalkms** [comment]
Why did it change the `detekt-config.yml` file?

**Comment by vanniktech** [comment]
Good question. I guess the ordering is not really stable.

**Comment by schalkms** [comment]
I've never had this problem before and I'm also on a Mac.

**Pull request merged**
