### PR TITLE
Migrate very first projects to gradle kotlin dsl

### PR DESCRIPTION
**Pull request by epeee**
A very first step towards #611.

### CODE REVIEW

**Comment by epeee** [comment]
Hmm, the travis build is failing while running detekt on the code base (during processing newly added kts files). Excluding kts files from the analysis (in io.gitlab.arturbosch.detekt.core.KtTreeCompiler#isKotlinFile) resolves the problem. 
Should we create a ticket for the problem and exclude kts files for now from the analysis?

**Comment by Mauin** [comment]
@epeee It looks like the Travis build succeeds in building the detekt `.jar`s. But then when testing the detekt codebase something goes wrong. If you build detekt locally and run 
`java -jar ./detekt-cli/build/libs/detekt-cli-*-all.jar -i . --baseline ./reports/baseline.xml -f ".*/resources/.*, .*/build/.*" -c ./detekt-cli/src/main/resources/default-detekt-config.yml,./reports/failfast.yml` you should be able to reproduce this.

**Comment by epeee** [comment]
@Mauin thx! 
I was able to track it down to the newly added kts files (see my previous comment/question).

**Comment by arturbosch** [comment]
Looks like there is a bug in LargeClass rule when analyzing kts files.
Have you tracked down the script file or is it happen for every script file?

**Comment by Mauin** [comment]
Yeah, seems to be a bug with Kotlin script files in the `LargeClass` complexity rule. I'm taking a look at how to fix it.

**Comment by Mauin** [comment]
I created #741 which should fix these issues. I ran the `build.gradle.kts` changes against my fixes and the build then fails for some real detekt violations. But at least the rules don't crash anymore 👍

**Comment by epeee** [comment]
@Mauin thx! 
I will have a look at the real detekt violations once your pr is merged.

**Comment by Mauin** [comment]
@epeee The PR is merged 🙃 Once you rebase you should be able to build the project and run detekt on the codebase. Let me know if you run into any other issues.

**Comment by epeee** [comment]
@Mauin thx!
I just rebased and fixed the violations.
Sadly, travisci is heading into the same problem as already fixed in #741 on master (while running ./gradlew detektCheck using the latest version 1.0.0.RC6-3).
It looks like we have to publish a new version which contains the fix and make use of it in this branch in order to get a green travis build.

**Comment by Mauin** [comment]
Eek. Right. That means the fixes in #741 definitely worked but we might need a new detekt release to get the build green. @arturbosch WDYT?

**Comment by epeee** [comment]
Yep, let's wait for RC7.
Do you have a rough estimate about RC7?
Looking forward to check kts files using detekt in other projects too.

**Comment by arturbosch** [comment]
Well not really, but personally I want to finish RC7 before march ^^

**Comment by epeee** [comment]
I just rebased and applied recent changes from gradle scripts. Therefore this one is ready for review now.

**Comment by arturbosch** [comment]
Looks and works great, even in IntelliJ :)

**Pull request merged**
