### PR TITLE
Add severity to Findings

### LINKED ISSUE #66: Support any common report file format
I'd like to support this in [Violations Lib](https://github.com/tomasbjerre/violations-lib). As requested in https://github.com/tomasbjerre/violations-lib/issues/19 .

I think it is a bit unclear how the output should be parsed. And a better solution might be if this tool could create a report in any common format.

For example ESLint can generate reports in the checkstyle format. Perhaps this tool can support generating report files in the checkstyle format?

### PR DESCRIPTION
**Pull request by winterDroid**
This is the first PR of 3 to fix #66 

Since reports should contain the severity of the found issue, I added that field to Findings.
Maybe it would be even nicer at some point to separate the Rule metadata from the Rule itself and report findings through a shared context. This would be similar to Lint Detector/Context/Issue setup.

### CODE REVIEW

**Comment by winterDroid** [comment]
Unfortunately I can't use this PR as a base for the upcoming PRs. Here you can find the other branches:
- https://github.com/winterDroid/detekt/tree/output_baseline_file to support a file for output and baseline instead of report with flags
- https://github.com/winterDroid/detekt/tree/report_file_format to support different formatters for the to be created report

**Comment by arturbosch** [comment]
Heyho thx for the pr!
maybe you can just merge everything into this PR, would be easier to review and merge this.

>Maybe it would be even nicer at some point to separate the Rule metadata from the Rule itself and report findings through a shared context. This would be similar to Lint Detector/Context/Issue setup.

That sounds interesting, can you give more input on this?

**Comment by arturbosch** [comment]
Too bad I forgot that the Finding should have the severity field too :(.

Maybe it's time for an `addCodeSmell(element: PsiElement)` method inside `Rule` as `addFindings(CodeSmell(id, severity, Entity.from(it)))`  is the common pattern for most rules. This rule must call `addFindings` as Suppresion is checked here. Maybe `addFinding` without the vararg too ...

**Comment by arturbosch** [comment]
I don't quite like the extra dependency on commons-lang just for one class as Kotlin is our utils library :). Extracting `StringEscapeUtils.escapeXml10()` is quite hard though ... maybe we can copy the `XmlEscapers` class from guava?

**Comment by winterDroid** [comment]
Created a new PR #67 with the final version

**Pull request closed without merging**
