### PR TITLE
Added more exception rules

### PR DESCRIPTION
**Pull request by schalkms**

### CODE REVIEW

**Comment by schalkms** [comment]
@vanniktech if you check the .yml file
exceptions:
  active: true

**Comment by vanniktech** [comment]
Should not each rule have it's own entry though?

**Comment by schalkms** [comment]
All rules in this package are added by default.

**Comment by arturbosch** [comment]
Ok, I will need more time with this one, thanks for the contributions!

Just linking #95, where all Throw- and Catch- rules should be refactored using a MultiRule + configurations.

**Pull request merged**
