### PR TITLE
Update FunctionNaming regex to work for sentences

### LINKED ISSUE #423: FunctionNaming regex should work for test cases that are sentences
Currently the regex for FunctionNaming is too specific to allow for tests that use the sentence syntax, a massive boom for readability.

```
fun `Test doUpcast() upcasts ExpenseProvided to created, candidate and qualifying events`() {
}
```

should be fine, but because it starts with a capital, has spaces, and is surrounded by backticks, it does not pass the test. 

a regex like this should work ``` ^([a-z$][a-zA-Z$0-9]*)|(`.*`)$ ```

### PR DESCRIPTION
**Pull request by snowe2010**
Currently the FunctionNaming regex does not match for kotlin backtick
sentence style. This sentence style is very useful in tests.

This is an update to the regex that, if the function name begins with
backticks, to accept it no matter what

Closes #423

### CODE REVIEW

**Comment by snowe2010** [comment]
@schalkms anytime I try to run spek tests I receive the error 

```

Sep 22, 2017 2:01:03 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'spek' failed to discover tests
java.lang.IllegalAccessError: tried to access method org.junit.platform.engine.support.descriptor.ClassSource.<init>(Ljava/lang/Class;)V from class org.jetbrains.spek.engine.SpekTestEngine
        at org.jetbrains.spek.engine.SpekTestEngine.resolveSpec(SpekTestEngine.kt:114)
        at org.jetbrains.spek.engine.SpekTestEngine.resolveSpecs(SpekTestEngine.kt:68)
        at org.jetbrains.spek.engine.SpekTestEngine.discover(SpekTestEngine.kt:50)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:65)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:57)
        at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:57)
        at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:84)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:74)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:47)
        at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:39)
```

From command line and intellij. I wrote an extra test, but can't actually run it 😂

**Comment by schalkms** [comment]
Yes, see issue #410 
At the moment I'd just write a JUnit test.

**Comment by snowe2010** [comment]
This test should pass as soon as #431 is merged.

**Comment by arturbosch** [comment]
Please also update the `default-detekt-config.yml` file inside the cli resources. There you can basically override the pattern which is preconfigured to the old value. Thanks!

**Comment by snowe2010** [comment]
@arturbosch default config regex has been updated

**Comment by arturbosch** [comment]
Cool, glad to merge this after the test fix pr :)

**Pull request merged**
