### PR TITLE
Introduce lock-bot

### PR DESCRIPTION
**Pull request by schalkms**
https://github.com/apps/lock

### CODE REVIEW

**Comment by schalkms** [comment]
Was it intentional to merge this PR into the **arturbosch:lock-bot** branch?

**Comment by arturbosch** [comment]
Mh, no not at all. I just clicked the merge button :(.
Could you reopen a PR?

**Comment by schalkms** [comment]
It was my mistake. GitHub automatically selected the wrong base branch, which is weird.
I created a new PR.

**Comment by vanniktech** [comment]
GitHub notifications from Detekt just got so unusable. I've gotten 300+ for all the issues. What' the incentive here? I don't see any value in such bot except that it's spamming the project notifications and I'm super close to turning off all of the notifications

**Comment by arturbosch** [comment]
I hope this will stop when all ~900 PRs and ~700 issues are locked ;).
Many old conversations got revived instead of opening new issues. Hard to manage them ^^

**Comment by vanniktech** [comment]
Yeah, in the end, I decided to mark all as read and stop watching this repository :man_shrugging: 
I don't see a benefit in the bot either

**Comment by schalkms** [comment]
@vanniktech we are sincerely sorry for the inconvenience we caused and for flooding your mailbox.
As always, we value your honest feedback.
Due to the growing popularity of this repository, we needed assistance to manage these old issues.
I'm not watching every old issue and managing them after some time becomes a hassle.
The notifications will stop, since the bot completed it's work for now.

We could change the bot to not comment on the issues. This would prevent problems like this in the future. What do you think?

> I hope this will stop when all ~900 PRs and ~700 issues are locked ;).
PRs are excluded from this.

**Comment by vanniktech** [comment]
> We could change the bot to not comment on the issues. This would prevent problems like this in the future. What do you think?

That would be nice. Also, everyone who wrote to a particular issue or commented on it would be spared by the bot.

> I'm not watching every old issue and managing them after some time becomes a hassle.

I've been watching every issue for the last 12+ months and for this project there's barely been any activity on old issues.

**Comment by arturbosch** [comment]
> We could change the bot to not comment on the issues. This would prevent problems like this in the future. What do you think?

I highly +1 for this. Can you please provide a PR and merge it asap? Thanks you.

**Comment by cortinico** [comment]
> I highly +1 for this. Can you please provide a PR and merge it asap? Thanks you.

I got the same problem, my inbox was also flooded of emails 😅 
Here the fix #1716 

> I've been watching every issue for the last 12+ months and for this project there's barely been any activity on old issues.

Same here. I do believe that locking old issues is valuable, but I've been watching the repo for some months and I haven't seen much activity on old issues.

**Comment by schalkms** [comment]
I think we can conclude, that we should wait longer (for feedback) till we merge PRs.
This would have prevented this issue from happening.
We have violated our own contribution guideline. I think we should be more careful here.
To cite our guideline.
> be aware that your PR will stay open for at least two days so that other users can give feedback.

**Pull request merged**
