### PR TITLE
Gradle 6

### LINKED ISSUE #2040: Issues with Gradle 6.0-rc-1
When I try to run _detekt 1.1.1_ with _Gradle 6.0 rc1_ I get the following output:

```
> Task :detekt
Property 'baseline' of mutable type 'org.gradle.api.file.RegularFileProperty' is writable. Properties of this type should be read-only and mutated via the value itself. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'config' of mutable type 'org.gradle.api.file.ConfigurableFileCollection' is writable. Properties of this type should be read-only and mutated via the value itself. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'filters' of mutable type 'org.gradle.api.provider.Property' is writable. Properties of this type should be read-only and mutated via the value itself. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'plugins' of mutable type 'org.gradle.api.provider.Property' is writable. Properties of this type should be read-only and mutated via the value itself. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'reportsDir' of mutable type 'org.gradle.api.provider.Property' is writable. Properties of this type should be read-only and mutated via the value itself. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
```

### PR DESCRIPTION
**Pull request by 3flex**
See #1820 for background.

Gradle 5.0 is now the lowest compatible version (not easy or perhaps even possible to support 4.x and 6.x at the same time).

Fixes #2040

### CODE REVIEW

**Comment by arturbosch** [comment]
Gradle 5.0 is from Dezember 2018. I'm okay with having it as the minimum supported version ^^ :+1:

**Comment by arturbosch** [comment]
So version 6 will be the next Gradle release this month.
Lets release a version 1.1 with Gradle 4.10 support and merge this for 1.2 preparations @schalkms @3flex

**Comment by 3flex** [comment]
Yep, no rush on this. In fact I wouldn't want to merge this until 6.0 stable is out - there might be more changes or deprecations to be made to the current version of the plugin first.

**Comment by arturbosch** [comment]
This PR is not affected by the build failure at master.

**Comment by arturbosch** [comment]
:1st_place_medal:

**Pull request merged**
