### PR TITLE
Add Rule NewlineAtEndOfFile.

### LINKED ISSUE #181: Rule NewlineAtEndOfFile
Reports if there's no new line at the end of a file.

Inspired by the [rule from Checkstyle](http://checkstyle.sourceforge.net/config_misc.html#NewlineAtEndOfFile).

### PR DESCRIPTION
**Pull request by vanniktech**
Fixes #181

### CODE REVIEW

**Comment by arturbosch** [comment]
That's something we can auto correct. Should we move that to formatting?

**Comment by vanniktech** [comment]
I think having both would be beneficial. I'm not using the auto formatting and would like to get it flagged.

**Comment by arturbosch** [comment]
You can run the formatting without auto correcting ^^. It is basically the decision in which rule set it will come and I think formatting is more appropriate as we can auto correct this one.

Ofc its the dilema that it also fits into style and should we provide more formatting rules if #38 is unclear

**Comment by vanniktech** [comment]
Hmm how about getting this merged first and then see whether we can improve the auto formatting?

**Comment by arturbosch** [comment]
I don't mind, maybe we tackle formatting 1.1 ^^

**Comment by vanniktech** [comment]
Sounds good 👍

**Pull request merged**
