### PR TITLE
Remove duplicated test task setup for gradle plugin

### PR DESCRIPTION
**Pull request by arturbosch**

### CODE REVIEW

**Comment by arturbosch** [comment]
Travis stopped working?!

**Comment by schalkms** [comment]
@arturbosch there were some issues in the past days. One reason was an extended maintenance period. I noticed that and had to restart several builds. Most of them were MacOS builds.

**Comment by schalkms** [comment]
It seems like people contribute more to open source and thus trigger more CI builds, since Covid hit Europe and America.

**Comment by schalkms** [comment]
It's funny. PR #2504 works fine on TravisCI.

**Comment by arturbosch** [comment]
Hehe right :).

I'm currently taking a look at https://github.com/marketplace/actions/gradle-command.
Maybe it is worth to migrate to GitHub actions to have all platforms in one CI tool...

**Comment by schalkms** [comment]
> I'm currently taking a look at https://github.com/marketplace/actions/gradle-command.
Maybe it is worth to migrate to GitHub actions to have all platforms in one CI tool.

This project looks promising. The question remains how stable and mature it is.

Btw AppVeyor also has outages if you look at the latest commits on master.

**Pull request merged**
