### PR TITLE
More descriptions to for most rules

### PR DESCRIPTION
**Pull request by Mauin**
This PR adds more descriptions to most rules.

It's still missing a description for `EqualsWithHashCodeExist` and `FeatureEnvy`. Open for suggestions for those to have descriptions for all rules.

### CODE REVIEW

**Comment by arturbosch** [comment]
Looks good. Will provide some suggestions later :), big thx you!

It seems deteKt does not like these long lines now :D

Maybe we should same all the default descriptions inside a property file and load them on startup? This would not only remove the MaxLineLength violations but also have them all in one place to correct, extend or change them ..?

**Comment by Mauin** [comment]
I split up the `Issue` construction in each rule over multiple lines to avoid the `MaxLineLength` issue. Generally I think it's better keeping the description in the rule class itself. That makes it easier to see what the issue should intends to report and how it might behave. Kind of like some additional documentation for the rule class.

**Comment by Mauin** [comment]
Updated this PR with the last descriptions. Sorry for the long delay 😕

**Comment by arturbosch** [comment]
No problem! Thank you for the big help! It seems, we will have M13 today :+1:

**Pull request merged**
