### PR TITLE
Added missing rules to detekt-config

### PR DESCRIPTION
**Pull request by schalkms**
This stuff needs to be generated automatically.
It seems like detekt really needs feature #343 and #189 

And why is `FeatureEnvy` commented out?

### CODE REVIEW

**Comment by arturbosch** [comment]
Looks like this happened when I merged my PRs for rc4-3 :/

**Comment by arturbosch** [comment]
I try to tackle automation when it's time writing the documentation...

The feature envy smell needs type resolution so I stopped working on that rule.

**Comment by schalkms** [comment]
@arturbosch Thanks for the response.
Let us know if you need help with the documentation features.

**Comment by arturbosch** [comment]
The documentation idea was mainly split the readme into different sections for a wiki and check if it needs updates/rework + find features which are not described. KDoc for each rule is also necessary for the generation issue. If you are interested , you can proposals for the WIKI (eg. PR with a folder with md files).

**Pull request merged**
