### PR TITLE
Align ModifierOrder check with official Kotlin coding conventions

### PR DESCRIPTION
**Pull request by 3flex**

### CODE REVIEW

**Comment by schalkms** [comment]
@vanniktech yes, it makes sense to compare the changes with the current test cases.

**Comment by 3flex** [comment]
@Mauin sorry I missed that! Updated.
@vanniktech @schalkms any updates required? I looked at the test cases and they don't need any changes to test the positive and negative cases.

**Comment by vanniktech** [comment]
Then let's add one that verified the correct behavior?

**Comment by 3flex** [comment]
Do you mean in addition to https://github.com/arturbosch/detekt/blob/master/detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/ModifierOrderSpec.kt?

There are already some test cases there that check this rule - or am I misunderstanding?

**Comment by vanniktech** [comment]
While there are some test cases they didn't test all of the modifiers. I'd just add 1-2 test cases for some of the modifiers that got swapped like internal and expect.

**Comment by 3flex** [comment]
I've added a couple of additional tests covering the `actual` and `varargs` keywords. Hopefully this will suffice.

**Comment by 3flex** [comment]
Triggering a new Travis build.

**Pull request merged**
