### PR TITLE
Run cli on ci

### PR DESCRIPTION
**Pull request by arturbosch**

### CODE REVIEW

**Comment by Mauin** [comment]
Should we also run `-i .` to just let detekt perform a cli run over the codebase?

**Comment by arturbosch** [comment]
Yes maybe so the newest built version is tested too (updating detekt-gradle can only be done after a new release is out)

**Comment by rock3r** [comment]
Looks like the `gradlew detektCheck` is run differently from the CLI, using a different configuration, hence that one is not failing but the CLI is.

**Comment by arturbosch** [comment]
Yes, detektCheck uses the latest release version and the CLI run is the current state of the master

**Comment by rock3r** [comment]
Maybe it's just a matter of decoupling the project's settings and the defaults? Or use the project's defaults for both. Or, if in the end we don't care whether the CLI run actually passes but only if it runs, we can `|| true` the exit code of the command.

**Comment by arturbosch** [comment]
I like having the current release version tested on Detekt + contributors get instant feedback for their new rules on detekt. But yes first I just wanted to test if the cli starts. The gradle plugin just calls the main function so the functionality is the same.

Will rebase/merge this after #289 is merged.

**Pull request merged**
