### PR TITLE
update kotlin to v1.1.4

### LINKED ISSUE #244: Update to kotlin 1.1.4 asap
https://youtrack.jetbrains.com/issue/KT-18475
https://youtrack.jetbrains.com/issue/KT-16497

Cannot access internals:
- Int.reached
- Project.fallbackArguments

### PR DESCRIPTION
**Pull request by Mauin**
release notes:
https://blog.jetbrains.com/kotlin/2017/08/kotlin-1-1-4-is-out/

Resolves #244

### CODE REVIEW

**Comment by arturbosch** [comment]
maeh I still have the internal visibility problems :(

**Comment by Mauin** [comment]
Did you update the IntelliJ plugin?

**Comment by arturbosch** [comment]
Getting the error mention from console ...

**Comment by Mauin** [comment]
It worked for me and also the CI build on Travis was working fine.

**Comment by arturbosch** [comment]
I had to `gradle clean`. Now everything works :3

**Comment by Mauin** [comment]
Great! 🎉

**Pull request merged**
