### PR TITLE
[WIP] Windows support

### PR DESCRIPTION
**Pull request by arturbosch**

### CODE REVIEW

**Comment by arturbosch** [comment]
@sschuberth heyho can pls test this build?

`gradle build install shadow`

Using the Cli with `--project` and `--config`
You can check the gradle-plugin on detekt itself, the versions should be ok (as gradle install overrides 1.0.0.M12.1)

**Comment by sschuberth** [comment]
For me already `gradle build` fails with:

```
Failures (1):
  JUnit Jupiter:ConditionalPathVisitorTest:test()
    MethodSource [className = 'io.gitlab.arturbosch.detekt.formatting.visitors.ConditionalPathVisitorTest', methodName = 'test', methodParameterTypes = '']
    => java.lang.AssertionError:
Expecting:
 <0>
to be equal to:
 <5>
but was not.

Test run finished after 1728 ms
[        21 containers found      ]
[         0 containers skipped    ]
[        21 containers started    ]
[         0 containers aborted    ]
[        21 containers successful ]
[         0 containers failed     ]
[        55 tests found           ]
[         0 tests skipped         ]
[        55 tests started         ]
[         0 tests aborted         ]
[        54 tests successful      ]
[         1 tests failed          ]

:detekt-formatting:junitPlatformTest FAILED
```

**Comment by sschuberth** [comment]
I deleted my previous comment as I was testing the wrong branch, `master` instead of `windows`. However, the `windows` branch yields the same errors. I'll try to look into it.

**Comment by sschuberth** [comment]
Ok, so with #136 and #137 merged in addition to this PR `gradle build install shadow` works fine for me on Windows.

**Comment by arturbosch** [comment]
Awesome will check the PR's out in one or two hours , big thx !!

**Comment by arturbosch** [comment]
Did you also checked out `gradle detektCheck` on detekt itself?

**Comment by arturbosch** [comment]
I managed to `gradle build install shadow detektCheck detektFormat` on my virtual Windows!

**Comment by sschuberth** [comment]
Great, so looks like we're good to merge! :-)

**Comment by arturbosch** [comment]
oh man ... xD

**Comment by sschuberth** [comment]
The history in the `windows` branch is now pretty much messed up, there are multiple times the same commit message of mine, but the changes are not mine, but at least it's merged now 😉

**Comment by arturbosch** [comment]
Yeah ... sorry for that, normally there is a `git merge --rebase` automatically, but because I pulled too many changes from `master` and did a `git rebase --incremental` to delete/rewrite my `\n` mistake, I pretty much destroyed the history xD. Rebase again on master had too many conflicts, so yeah I just merged it xD

**Comment by arturbosch** [comment]
I hope I did not steal your

**Comment by sschuberth** [comment]
> did a `git rebase --incremental`

I guess you mean `--interactive`? BTW, note that you usually also want to pass `--preserve-merges` if you rebase a branch that has merge commits.

> I hope I did not steal your commits ...

No worries, it's more the opposite: At least one of your commits now looks as if it was done by me 😉

**Pull request merged**
