### PR TITLE
Added allowedExceptionNameRegex config for EmptyCatchBlock

### PR DESCRIPTION
**Pull request by schalkms**
reference #734

### CODE REVIEW

**Comment by schalkms** [comment]
@vanniktech
I do not think that detekt should have default values here. I dislike the fact that are empty catch blocks in a codebase. I understand that it might be necessary sometimes, but I would not add any defaults here. I think this decision should be up to the user.

**Comment by vanniktech** [comment]
Usually when an exception is named like one of these the IDE also understands this and then does not flag it.

**Comment by schalkms** [comment]
Ok. What do you think? @arturbosch

**Comment by arturbosch** [comment]
I would go with the intellij default which is `ignored` like @vanniktech suggested ^^

**Comment by vanniktech** [comment]
Let's also include `expected`? I use that often when writing tests.

**Pull request merged**
