### PR TITLE
WIP: Detekt IntelliJ Plugin

### PR DESCRIPTION
**Pull request by deeprim**

### CODE REVIEW

**Comment by arturbosch** [comment]
Hey, thanks for the contribution! 
RC6.3 has a bug with kts files, so its not your fault that the build fails ^^
For now you can add the build.gradle.kts into the `filter` parameter.

**Comment by arturbosch** [comment]
Hey, when running `gradle runIdea` and opening the file `DetektFacade` i promptly get an exception

```
annotator: io.gitlab.arturbosch.detekt.DetektAnnotator@13b9541f (class io.gitlab.arturbosch.detekt.DetektAnnotator)
java.lang.Throwable
	at com.intellij.util.ExceptionUtil.currentStackTrace(ExceptionUtil.java:65)
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:486)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:112)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.process(ExternalToolPass.java:226)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:217)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:36)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:155)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:242)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by deeprim** [comment]
Hi @arturbosch, the error was caused by `ConcurrentModificationException` within `io.gitlab.arturbosch.detekt.rules.style.UnusedPrivateMember`, it doesn't reproduce all the time though

**Comment by arturbosch** [comment]
Hey, it should be fixed on the master, could you rebase your branch and fix the `ReturnCount` issue, then I'm more than happy to merge this :+1:

**Comment by misaelmt** [comment]
I rebased and got this in Android Studio:

`java.lang.NoClassDefFoundError: io/gitlab/arturbosch/detekt/core/ProcessingSettings
	at io.gitlab.arturbosch.detekt.DetektAnnotator.processingSettings(DetektAnnotator.kt:70)
	at io.gitlab.arturbosch.detekt.DetektAnnotator.doAnnotate(DetektAnnotator.kt:40)
	at io.gitlab.arturbosch.detekt.DetektAnnotator.doAnnotate(DetektAnnotator.kt:20)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:214)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:36)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:155)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:242)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by deeprim** [comment]
Hi @misaelmt ,
How did you build the plugin? It should be built with `buildPlugin` task, I've checked with latest Android Studio - works fine.

**Comment by misaelmt** [comment]
Hi @deeprim! Thanks for your reply.
Using the latest version from this PR, I built with `./gradlew :detekt-intellij-plugin:buildPlugin` 
And installed the plugin by browsing to build/distributions/Detekt IntelliJ Plugin-1.0.0.zip (also tried with build/libs/detekt-intellij-plugin-1.0.0.jar)

`./gradlew runIdea` Works! I see all the issues highlighted in the ComplexClass test case.
**Android Studio 3.0.1** It doen't crash but the issues are not highlighted.
**IntelliJ IDEA Ultimate 2017.3.4** It doen't crash but the issues are not highlighted.
**Android Studio 3.2 Canary 6** It crashes with this exception:
`annotator: io.gitlab.arturbosch.detekt.DetektAnnotator@771483f8 (class io.gitlab.arturbosch.detekt.DetektAnnotator)
java.lang.Throwable
	at com.intellij.util.ExceptionUtil.currentStackTrace(ExceptionUtil.java:65)
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:486)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:112)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.process(ExternalToolPass.java:226)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:217)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:36)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:155)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:242)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

What I'm doing wrong?

**Comment by arturbosch** [comment]
It works for me and looks great! :+1: 
@misaelmt you have detekt activated in the settings? (Ctrl+Shift+A, type detekt, goto settings/detekt)

The build time is not much longer than without the plugin. I hope travis will successfully cache the idea distribution ^^

Please do a rebase so I can merge this ^^

**Comment by misaelmt** [comment]
@arturbosch Yes, I activated detekt. I also tried enabling/disabling it, enabling/disabling detekt for tests, and using different config files.

**Comment by arturbosch** [comment]
Hmm, I do not know why, but still I think we should merge this into master for less conflicts (incubating status).

**Comment by deeprim** [comment]
Hello @misaelmt, @arturbosch,

The error may be caused by a failed rule (IntelliJ should provide the original stacktrace as a separate entity in the error report window).

After IntelliJ catches an error from a plugin it may mark it as "bad" and silently disable it. (that's why you may see the plugin not working).

**Pull request closed without merging**
