### PR TITLE
Deploy SNAPSHOTs automatically

### LINKED ISSUE #1826: SNAPSHOT process feedback
(I noticed these because I'm looking for a version to pull in to try #1818)

---

It looks like SNAPSHOT builds are not published any more. The last version is [`detekt-cli-1.0.0-20190804.140139-1.jar`](https://oss.jfrog.org/artifactory/webapp/#/artifacts/browse/tree/General/oss-snapshot-local/io/gitlab/arturbosch/detekt/detekt-cli/1.0.0-SNAPSHOT/detekt-cli-1.0.0-20190804.140139-1.jar) (acf2e3b7b00f42c4ff67558cd0dabcc5531a8a93) 14 days ago, it looks like SNAPSHOT publishing has been down on master builds between 996139d507f9fe6bf1e01bb08fb433a1d9aa34cd..bb404007ac7fa859462775d599f537f7d7b1bd5e

---

Additionally I think
https://github.com/arturbosch/detekt/blob/bb404007ac7fa859462775d599f537f7d7b1bd5e/gradle.properties#L1
should be updated with a commit right after tagging the released version in git, because otherwise you end up with these artifacts:
```
1.0-SNAPSHOT 20190804.123456-1
1.0-SNAPSHOT 20190810.123456-1
1.0
1.0-SNAPSHOT 20190812.123456-1
1.0-SNAPSHOT 20190823.123456-1
1.1
1.1-SNAPSHOT 20190827.123456-1
```
while it should be named like this by convention (note the version in front):
```
1.0-SNAPSHOT 20190804.123456-1
1.0-SNAPSHOT 20190810.123456-1
1.0
1.1-SNAPSHOT 20190812.123456-1
1.1-SNAPSHOT 20190823.123456-1
1.1
1.2-SNAPSHOT 20190827.123456-1
```
after release the SNAPSHOT is a preliminary published version of the next release not the just-released version.

### PR DESCRIPTION
**Pull request by BraisGabin**
I just added the execution permission to the file `.buildscript/deploy_snapshot.sh` with `chmod +x .buildscript/deploy_snapshot.sh`.

And I changed the SDK to one that we are using already.

You can see here that it was failing for that reason: https://travis-ci.org/arturbosch/detekt/jobs/607791661#L3885-L3886

Fixes #1826

### CODE REVIEW

**Comment by BraisGabin** [comment]
Yes, that's correct. But if you check near the file name you can see the change: `100644 → 100755`

**Comment by schalkms** [comment]
Uh, yes. It's a bit hidden. Cool, thanks!

**Comment by BraisGabin** [comment]
🎉 It works! https://oss.jfrog.org/artifactory/webapp/#/artifacts/browse/tree/General/oss-snapshot-local/io/gitlab/arturbosch/detekt/detekt-cli/1.1.1-SNAPSHOT

**Comment by arturbosch** [comment]
Awesome!

**Pull request merged**
