### PR TITLE
Downgrade to jcommander v1.72

### PR DESCRIPTION
**Pull request by schalkms**

### CODE REVIEW

**Comment by 3flex** [comment]
What's the reason for the downgrade?

**Comment by schalkms** [comment]
> What's the reason for the downgrade?

@3flex please take a look at #1805

**Comment by sschuberth** [comment]
@schalkms The rationale for such changes should go into the commit message, IMO.

**Comment by arturbosch** [comment]
@sschuberth thanks for the reminder TIL. :)

**Comment by schalkms** [comment]
@sschuberth I should have linked the issue. Thanks for the hint!

**Pull request merged**
