### PR TITLE
FindBugs XML report

### PR DESCRIPTION
**Pull request by remal**
`FindBugsXmlOutputReport` has been added. Tests are included.

### CODE REVIEW

**Comment by remal** [comment]
@arturbosch @schalkms Could you please take a look?

**Comment by 3flex** [comment]
Is the checkstyle XML report not sufficient?

**Comment by remal** [comment]
@3flex Checkstyle reports don't have issue descriptions, but FindBugs - have

**Comment by remal** [comment]
@arturbosch 
FindBugs XML report can handle classes and methods. But I haven't found a way to get classes and methods from Detekt. So I decided to output only files and file positions.

I've tested the report against my own parser, but I've **not** tested the report against these libraries. Maybe it makes sense to think about creating such test... WDYT?

**Comment by arturbosch** [comment]
@remal yes please use https://github.com/tomasbjerre/violations-lib as testImplementation for detekt-api and test the parsing. They spend quite a bit on parsing Findbugs.

**Pull request closed without merging**
