### PR TITLE
Build improvements

### PR DESCRIPTION
**Pull request by mkobit**

### CODE REVIEW

**Comment by Mauin** [comment]
Travis is broken because `./gradlew shadow` now resolves to multiple tasks so gradle fails.

**Comment by arturbosch** [comment]
Oh no. Does shadow plugin 2.0 wants us to use `shadowJar` now because there are more shadow tasks? Please change the travis script too and thanks for the contribution!

**Comment by mkobit** [comment]
One weird thing now with newer version of Shadow (which seems like issue with how Shadow maps inputs/outputs) is this output:

```
> Task :detekt-cli:shadowJar UP-TO-DATE                        
A problem was found with the configuration of task ':detekt-cli:shadowJar'. Registering invalid inputs and outputs via TaskInputs and TaskOutputs methods has been deprecated and is scheduled to be removed in Gradle 5.0.                                   
 - No value has been specified for property 'mainClassName'.   

> Task :detekt-cli:startShadowScripts UP-TO-DATE               
Using TaskInputs.file() with something that doesn't resolve to a File object has been deprecated and is scheduled to be removed in Gradle 5.0. Use TaskInputs.files() instead.                

> Task :detekt-watch-service:shadowJar UP-TO-DATE
A problem was found with the configuration of task ':detekt-watch-service:shadowJar'. Registering invalid inputs and outputs via TaskInputs and TaskOutputs methods has been deprecated and is scheduled to be removed in Gradle 5.0.                         
 - No value has been specified for property 'mainClassName'. 
```

Despite that, still running `java -jar detekt-cli/build/libs/detekt-cli-1.0.0.RC5-3-all.jar` and `java -jar detekt-watch-service/build/libs/detekt-watch-service-1.0.0.RC5-3-all.jar` both seem to work appropriately.

**Comment by 3flex** [comment]
Should update README as well, it says to use `./gradlew build shadow` but will have to change to `./gradlew build shadowJar` - https://github.com/arturbosch/detekt/blob/master/README.md#build--use-the-commandline-interface

**Comment by arturbosch** [comment]
Thanks `shadowJar` works for me without any warnings. Unfortunately the `install` tasks does not work anymore:

```
> Could not publish configuration 'archives'
   > A POM cannot have multiple artifacts with the same type and classifier. Already have MavenArtifact detekt-cli:zip:zip:null, trying to add MavenArtifact detekt-cli:zip:zip:null
```

**Comment by arturbosch** [comment]
Seems like the maven plugin and the task `install` is deprecated. detekt already has the `maven-publish` plugin and `publishToMavenLocal` does work. Can you please remove the this line `apply plugin: 'maven'
`? Thanks!

**Comment by arturbosch** [comment]
Thanks, everything works! :)

**Comment by mkobit** [comment]
Awesome, thanks! Looking forward to hopefully contributing a few more things here, going to try and tackle some Gradle improvements soon now that I have started to use this project!

**Comment by arturbosch** [comment]
Would love to see more :D! :+1:

**Pull request merged**
