### PR TITLE
Update Kotlin to 1.3.20

### PR DESCRIPTION
**Pull request by schalkms**

### CODE REVIEW

**Comment by schalkms** [comment]
Looks like a KtLint problem
I tag it as blocked.

```
io.gitlab.arturbosch.detekt.formatting.KtLintIntegrationSpec > it should work like KtLint FAILED
    java.lang.NoSuchFieldError: LONG_STRING_TEMPLATE_ENTRY
        at com.github.shyiko.ktlint.ruleset.standard.StringTemplateRule.visit(StringTemplateRule.kt:29)
        at io.gitlab.arturbosch.detekt.formatting.FormattingRule.apply(FormattingRule.kt:64)
        at io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule$visit$2$$special$$inlined$forEach$lambda$1.invoke(KtLintMultiRule.kt:84)
        at io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule$visit$2$$special$$inlined$forEach$lambda$1.invoke(KtLintMultiRule.kt:44)
        at io.gitlab.arturbosch.detekt.api.MultiRule.runIfActive(MultiRule.kt:27)
        at io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule$visit$2.invoke(KtLintMultiRule.kt:84)
        at io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule$visit$2.invoke(KtLintMultiRule.kt:44)
        at io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.visitTokens(KtLintMultiRule.kt:96)
        at io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.visit(KtLintMultiRule.kt:82)
        at io.gitlab.arturbosch.detekt.api.BaseRule.visitFile(BaseRule.kt:36)
        at io.gitlab.arturbosch.detekt.api.RuleSet.accept(RuleSet.kt:23)
        at io.gitlab.arturbosch.detekt.formatting.KtLintIntegrationSpec$1$1$1.invoke(KtLintIntegrationSpec.kt:23)
        at io.gitlab.arturbosch.detekt.formatting.KtLintIntegrationSpec$1$1$1.invoke(KtLintIntegrationSpec.kt:13)
```

**Comment by vanniktech** [comment]
Yeah there's an open issue on their repo.

Yet another reason to ditch ktlint here.

**Comment by vanniktech** [comment]
https://github.com/shyiko/ktlint/issues/321

**Comment by schalkms** [comment]
Thanks for the reference.

**Pull request merged**
