### PR TITLE
[Prototype] Introduce Context and Issue for rules

### PR DESCRIPTION
**Pull request by winterDroid**
As mentioned in PR #74, this is a proposal to extract the finding collection and rule metadata responsibility from the rule itself. 

It should be now for example pretty straightforward to convert all the `EmptyRule`s and `ExceptionRule`s to one single rule each which has several issues. That should also increase the performance since multiple issues will be found in one run.

Since you mentioned threading concerns, I decided that the context won't be singleton, just that every rule has its own context.

### CODE REVIEW

**Comment by arturbosch** [comment]
Have you made some runs and observed the amount of findings on each run? The reason for the rule class to have a list of findings is that detekt is highly parallel. If we have one single context class some findings can disappear. Making the context's report method synchronized or using a ConcurrentList would slow down the whole analysis. I will make some performance checks the next days ^^

**Comment by winterDroid** [comment]
Yeah you mentioned that earlier. That's why I create a context for each rule. So it should essentially be the same as before regarding synchronization.

**Comment by arturbosch** [comment]
Oh then it's my fault. It's a big PR. Looking through changes at github is difficult, will check it out :)

**Comment by arturbosch** [comment]
I've started working on your PR, fixed some broken tests and now evaluating if the Issue and Context classes will make life easier ;)

**Comment by winterDroid** [comment]
Nice! I think most value brings the issue Metadata since it allows reporting multiple issues within one rule and to add multiple specific messages per finding. The context is basically just a nice to have because it separates the reporting logic more from the rule itself.

**Comment by arturbosch** [comment]
Yeah I see the big benefit of having this Issue class and be able to use it between Finding and Rule. Unfortunately there is a big problems with this approach: 

The `sonar-api` wants me to create `RuleDefinitions` for my rules. They can be written in Java code or XML. Having to maintain the creation of this RuleDefinitions would be too much effort. 

For now I use a ServiceLoader and load all `RuleSetProvider` classes which let me get an instance of all rules. Having an `Issue`-constant in a companion object wouldn't be so straigthforward. I could give the `Rule` an abstract property `Issue` which needs to be overriden. That would work, what do you think?

I'm also struggeling with the Context class. Adding this have inpact on everything  ~2k changes which destroys the git history. I'm now testing if the context class benefit can be obtained through delegation ^^

**Comment by winterDroid** [comment]
I'm unfortunately not familiar with sonar. Maybe you want to take a look at Android Lint - basically there each issue contains an implementation class. Such an implementation objects contains a class reference to the Detector that before the actual file scanning, so basically your rule. Besides that it has a scope on which kind of files to run, so basically whether test files, Java files, resources files,... Maybe that helps.

**Comment by winterDroid** [comment]
Maybe take a look here:
https://android.googlesource.com/platform/tools/base/+/master/lint/libs/lint-api
https://github.com/googlesamples/android-custom-lint-rules

**Comment by winterDroid** [comment]
Actually Lint uses also Psi Visitors under the hood which might be interesting for you to look at as well

**Pull request closed without merging**
