### PR TITLE
Updated kotlin version to 1.3.10

### PR DESCRIPTION
**Pull request by schalkms**

### CODE REVIEW

**Comment by Mauin** [comment]
fyi: this is not updating the kotlin version in the gradle plugin.

**Comment by 3flex** [comment]
> this is not updating the kotlin version in the gradle plugin

Maybe a comment in each build file that reminds anyone updating to update in both locations?

**Comment by arturbosch** [comment]
Again crash at jdk9+10, kotlin-native-utils what?
@3flex yes feel free to open a PR + add this to the contributing.md :)

**Comment by Mauin** [comment]
Can we try re-running this or create an issue describing what needs to be done to unblock this?

**Comment by schalkms** [comment]
Honestly, I have no idea what's causing the build error only on linux and jdk 9&10.
I force-pushed it once, but it didn't help.

**Comment by 3flex** [comment]
See https://github.com/arturbosch/detekt/pull/1350#issuecomment-442215532

I vote for dropping 9 & 10 from CI

**Comment by 3flex** [comment]
CI should go green if you rebase now that #1371 is merged

**Pull request merged**
