### PR TITLE
RuleProviderTest and cleanup of test-cases

### PR DESCRIPTION
**Pull request by schalkms**
@arturbosch I'd also like to test the processors for our metrics. However, I wasn't able to get a non-empty list of them. What `ProcessSettings` config do I need to create here?

```kotlin
val locator = FileProcessorLocator(ProcessingSettings(path))
val providers = locator.load() // list is always empty
```

### CODE REVIEW

**Comment by arturbosch** [comment]
If you want to load all processors you need to specify a `io.gitlab.arturbosch.detekt.api.FileProcessListener` file with the full qualified names of the processor classes in the `test/resources/META-INF/services`. I have such a file in the `cli` module, not in the `core` module as having two of these files in both `cli` and `core` overrides one of them.

**Comment by schalkms** [comment]
Well, I want to check if all implemented processors are defined in the respective file. The same which I did for the rule providers. I don't want to define a new file.

**Comment by arturbosch** [comment]
That's unfortunately not possible as the resources file is in the cli module ... You could move the test into the cli module for that.

**Comment by schalkms** [comment]
Thanks! I'll implement that in the near future.
This can be merged.

**Pull request merged**
