### PR TITLE
Revert "Check cross-module coverage with Jacoco"

### PR DESCRIPTION
**Pull request by 3flex**
Reverts arturbosch/detekt#1566

While the PR did successfully achieve the goal of improving the coverage by consolidating reports, I've just noticed that after merging to master Codecov reports were not being generated anymore.

Reverting for now so coverage reports hopefully come back online.

### CODE REVIEW

**Comment by 3flex** [comment]
No joy on this one either :(

I've contacted Codecov support.

**Comment by schalkms** [comment]
Please keep us updated. I also noticed that there are several problems with codecov.

**Comment by 3flex** [comment]
Since we're not paying for support, the response from Codecov support was to post on the [Codecov community website](https://community.codecov.io/). I haven't yet since it's low volume.

It's unfortunate since I think the coverage reports were providing a lot of value. Maybe this can be merged now, then hope for the best? It broke when the initial commit was merged to master so theoretically this will fix it 🤷‍♂️

**Comment by 3flex** [comment]
Closing... Appears reports are now being generated on some PRs? Very confusing.

**Comment by arturbosch** [comment]
On two of my open PRs the report did not show up :(

**Comment by 3flex** [comment]
It's frustrating. It only shows in PR if the coverage report is generated on master branch (otherwise there's nothing to compare to). Not sure why, but they're not consistently generated on each commit in the master branch.

That seems to have started when #1566 was merged, hence this PR to revert it.

I deleted the branch so can't reopen this, I suggest creating a new PR to revert #1566 and merging and see if that helps.

**Comment by arturbosch** [comment]
kk, thanks for the answer. I will revert it then.

**Pull request closed without merging**
