### PR TITLE
Prototype detekt watch service - run detekt on each file change

### PR DESCRIPTION
**Pull request by arturbosch**
Heyho,
I just hacked together an idea I recently had: a watch service.
It helps to check for code smells while coding. The advantage is that no startup overhead is needed.

Todo's:
- using the same arguments as in cli-module
- printing just the code smell, not the rule set ids
- writing some tests

### CODE REVIEW

**Comment by vanniktech** [comment]
Is this ready to be reviewed?

**Comment by arturbosch** [comment]
Yes, please! The prototype in the title is just to make clear it is an experiment. If you guys find it useful, we can integrate as a module. 

What is missing: using the same arguments as in cli-module and maybe printing just the code smell, not the rule set ids.

**Comment by schalkms** [comment]
Good idea!
How does it affect RAM/CPU?
You might also add some tests?

**Comment by arturbosch** [comment]
That's a good question. I check every second for file changes which results in 0-2% cpu usage on my laptop. It would be awesome if you two can check it out locally and measure/guess. Maybe it is also ok to look all 2, 3 or 5 seconds.

RAM - I'm not sure, will check it tomorrow. My guess would be: not that much, as all data is immediately lost ...

Will write down tests on my list :)

**Comment by schalkms** [comment]
Performing good on a 2,4 GHz Intel Quad Core i7.
This might be a good idea for an IntelliJ plugin.

**Comment by schalkms** [comment]
Maybe the watch service should react to keystrokes instead of running periodically?

**Comment by arturbosch** [comment]
I think intellij has quite a similar api for changes as java7 has. Silently updating a table and showing the results when the user tries to commit something ^^.

Is it even possible to react to key strokes when the program runs in a terminal?

**Comment by arturbosch** [comment]
Uff I screwed the PR xD

**Pull request merged**
