### PR TITLE
ComplexMethod: more detail massege with Mcc and function range

### PR DESCRIPTION
**Pull request by cyw3**
A similar PR may already be submitted!
Please search among the [Pull requests](https://github.com/arturbosch/detekt/pulls) before creating one.

Thanks for submitting a pull request! Please provide enough information so that others can review your pull request. Link to relevant issues if possible.

For more information, see the [CONTRIBUTING guide](https://github.com/arturbosch/detekt/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by BraisGabin** [comment]
Thanks for contributing to detekt! Could you provide a bit more of information? What's the problem that you are facing? What's exactly the output now vs the new one? And could you add a test to ensure this behavior?

**Comment by cyw3** [comment]
Yes.

1. What's the problem that you are facing?
I want to know the Mcc of the function and the text range of function, so that I can use these data to do more things. For example, the average cyclomatic complexity of each file and so on.

2. What's exactly the output now vs the new one?
The original output:

`	<error line="29" column="13" severity="warning" message="The function getInstance appears to be too complex." source="detekt.ComplexMethod" />`

the new one:
`	<error line="29" column="13" severity="warning" message="The function getInstance appears to be too complex.The Mcc is (3/1). The function range is (29,9):(38,10)" source="detekt.ComplexMethod" />`

**Comment by cyw3** [comment]
image
How about changing this line to:
`Entity.from(function),`

So that I can get the range of the function, not just the function name, and I will use it to custom report.

**Comment by arturbosch** [comment]
We made the change to report at the function identifier to not confuse the user by pointing at the start of the KDoc.
You should be able to get the function by querying `issue.entity.ktElement.getNonStrictParentOfType<KtNamedFunction>()`.

**Pull request closed without merging**
