### PR TITLE
Added rule for safe cast to config.yml

### PR DESCRIPTION
**Pull request by schalkms**

### CODE REVIEW

**Comment by vanniktech** [comment]
How is this different from #233?

**Comment by schalkms** [comment]
The config.yml includes the reference to the safe-cast rule now.

**Comment by vanniktech** [comment]
But there are many more changes included?

**Comment by schalkms** [comment]
Yeah I did it on the same branch as the previous merged pull request by mistake. I submit a new request if

**Comment by arturbosch** [comment]
Yes pls open a new PR for the change only :)

**Pull request closed without merging**
