### PR TITLE
Add MissingWhenCase rule

### LINKED ISSUE #269: MissingCases
A rule that detekts missing cases.

This could be useful when using `when` with enums or sealed classes.

[ErrorProne reference](https://github.com/google/error-prone/blob/master/docs/bugpattern/MissingCasesInEnumSwitch.md).

### PR DESCRIPTION
**Pull request by 3flex**
Closes #269

### CODE REVIEW

**Comment by neugaojin** [comment]
how to run with a BindingContext
I'm writing custom rules
run `./gradlew detekt`  But the `BindingContext` is BindingContext.EMPTY

**Comment by 3flex** [comment]
Use `./gradlew detektMain`. That experimental task should pass the correct classpath to detekt so it can generate BindingContext.

**Comment by neugaojin** [comment]
Thank you for your reply
But, Is this Task added to the release version?
i found the newest version is `1.0.0-RC15`
when i access plugin 1.0.0-RC15 and run `./gradlew detektMain`
i got the error :`Task 'detektMain' not found in root project `

**Comment by 3flex** [comment]
It should create a task for each sourceset if you are using 1.0.0-RC15 of the Gradle plugin. Try `gradlew tasks --group="verification"`, you should have a couple of tasks with description "EXPERIMENTAL & SLOW: Run detekt analysis for main classes with type resolution".

If not, please open a new issue so we can track it there.

**Comment by neugaojin** [comment]
There is no such a Task，I'll open a new issue, Thank you

**Comment by neugaojin** [comment]
> Use `./gradlew detektMain`. That experimental task should pass the correct classpath to detekt so it can generate BindingContext.

Sorry，another question
how to pass `classpath` with gradle task

**Comment by 3flex** [comment]
You'd set the value of the `classpath` parameter on the detekt task to whatever classpath your project needs to compile.

It won't be easy without the Kotlin JVM plugin applied and using the auto generated task (which will set the classpath parameter for you) so if you're doing it manually it might be difficult and I won't be able to provide any support

**Pull request merged**
